version: '3.8'


services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis
    
  orderingdb:
    image: mcr.microsoft.com/mssql/server  
  
  rabbitmq:
    image: rabbitmq:management-alpine
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile
      
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile
      
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/ApiGateway/Dockerfile